[workspace]
members = [
    "proto-def",
    "core-utils",
    "cloud-render-srv",
    "macroquad-client",
]
resolver = "2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'

[profile.dev]
opt-level = 0
debug = 1
