[package]
name = "avif_poc"
version = "0.1.0"
edition = "2021"

[dependencies]
aom-decode = { git = "https://gitlab.com/kornelski/aom-decode" }
image = "0.24"
anyhow = "1.0"
imgref = "1.10"
rgb = "0.8"
