[package]
name = "proto-definitions"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13"
tonic = { version = "0.12", default-features = false, features = ["codegen", "prost"] }

[build-dependencies]
tonic-build = { version = "0.12", default-features = false, features = ["prost"] }
