[workspace]
members = [
    "proto-definitions",
    "cloud-proxy-server",
    "minimal-tui-client",
    "chrome-test",
]
resolver = "2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "unwind"
strip = true
