[package]
name = "core-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
yuv = "0.1"
rgb = "0.8"
log = { workspace = true }
env_logger = { workspace = true }
chrono = "0.4.25"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
