[package]
name = "proto-def"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.10"
prost = "0.12"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
tonic-build = "0.10"
